version: '3.8'
services:
frontend:
build: ./frontend
ports:
- "3000:3000"
depends_on:
- backend
environment:
- NEXT_PUBLIC_BACKEND=http://backend:8080
backend:
build: ./backend
ports:
- "8080:8080"
volumes:
- ./data:/data
depends_on:
- worker
worker:
build: ./worker
volumes:
- ./data:/data
deploy:
resources:
limits:
memory: 1G
cpus: '0.5'
